# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Alexandr Popov
title: Software Engineer
email: alxs.popov@gmail.com
website: alxspopov.github.io

# Social links
# twitter_username: facespics
github_username:  alxspopov
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: alexandr-popov-9523aa83
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Alex and I'm a passioned about my work. As of now I have worked on a number of projects.
  I really enojoy solving complex tasks sometimes switching between roles of developer and researcher.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  It may sound strange, but there are other interests and hobbies, like rock climbing, running and sports in general.

# Footer
footer_show_references: true

# Build settings
# thanks to this guy =)
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
